'use client';
import Image from 'next/image';
import { useState } from 'react';
import { ArrowDownToLine, ArrowUpFromLine, Check, Coins, FlaskConical, Gem, Shield } from 'lucide-react';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Slider } from '@/components/ui/slider';
import { Field as AccessibleField } from '@base-ui/react/field';
import { PARTS, type PartId } from '@/lib/game/catalog';
import { DEFENSE_SLOTS, RUNNER_CLASSES } from '@/lib/game/economy';
import { allowedParts, type AxieLoadout as Loadout } from '@/lib/game/axie';
import { AxieLoadout } from './axie-loadout';
import { PartPicker } from './part-picker';
import { TOKENS, amount, formatted, type Save, type TokenId } from '@/lib/game/economy';
export function VaultEditor({save,onEdit,onFund,onWithdraw,onInspect,onLoadAxie,onLab,onBrowse,onRunnerClass}:{save:Save;onLoadAxie:(a:Loadout)=>void;onLab:()=>void;onBrowse:()=>void;onRunnerClass:(v:string)=>void;onEdit:(index:number,part:PartId,x:number)=>void;onFund:(token:TokenId,units:number)=>void;onWithdraw:(token:TokenId,units:number)=>void;onInspect:(part:PartId)=>void}){
  const [token,setToken]=useState<TokenId>('SLP'),[value,setValue]=useState('100'),[error,setError]=useState('');
  return <><AxieLoadout axie={save.axie} onLoad={onLoadAxie} onLab={onLab} onBrowse={onBrowse}/><section className="defense-card editor-card"><div className="card-overline"><span><Shield size={16}/> TU DEFENSA</span><span>{save.traps.length} DEFENSAS</span></div><p className="editor-description">El orden también importa: las defensas se combinan y las de apoyo protegen a sus aliadas.</p>{save.traps.map((t,i)=><div className="trap-editor" key={i}><div className="editor-part-top"><span className="slot-number">0{i+1}</span><PartPicker value={t.part} available={allowedParts(save.axie)} label={`Parte de la trampa ${i+1}`} onChange={p=>onEdit(i,p,t.x)}/><button className="part-inspect" onClick={()=>onInspect(t.part)} aria-label={`Ver habilidad de trampa ${i+1}`}><Image unoptimized width={128} height={100} src={PARTS[t.part].partImage} alt=""/></button></div><p className="editor-power">{PARTS[t.part].short}</p><AccessibleField.Root><AccessibleField.Label className="position-label"><span>Trampa {i+1} · posición</span><span>{Math.round((t.x-DEFENSE_SLOTS[i].x+2)/4*100)}%</span></AccessibleField.Label><Slider aria-label={`Posición de trampa ${i+1}`} value={[t.x]} min={DEFENSE_SLOTS[i].x-2} max={DEFENSE_SLOTS[i].x+2} step={0.25} onValueChange={v=>onEdit(i,t.part,Array.isArray(v)?v[0]:v)}/></AccessibleField.Root></div>)}<div className="runner-class"><span className="runner-label">Clase del asaltante de prueba</span><Select value={save.runnerClass??'Beast'} onValueChange={v=>{if(v)onRunnerClass(v);}}><SelectTrigger aria-label="Clase del asaltante de prueba"><SelectValue/></SelectTrigger><SelectContent>{RUNNER_CLASSES.map(c=><SelectItem key={c} value={c}>{c}</SelectItem>)}</SelectContent></Select></div><div className={`proof-status ${save.validated?'verified':''}`}><Check size={16}/><span>{save.validated?'Defensa validada y guardada':`${save.proofs}/2 recorridos consecutivos completados`}</span></div><p className="editor-footnote">Completa tu recorrido dos veces para validar la defensa. Cada cambio reinicia la validación.</p></section>
  <section className="loot-card fund-card"><div className="card-overline"><span><Coins size={16}/> TU COFRE</span><span className="tiny-badge">DEMO</span></div><div className="chest-balances">{TOKENS.map(t=><div key={t}><span>{t==='SLP'?<FlaskConical size={15}/>:t==='AXS'?<Gem size={15}/>:<Shield size={15}/>} {t}</span><strong>{formatted(save.chest[t])}</strong></div>)}</div><form onSubmit={e=>{e.preventDefault();try{const units=amount(value);onFund(token,units);setError('');}catch(err){setError(err instanceof Error?err.message:'No se pudo guardar.');}}}><label htmlFor="fund-amount">Añadir botín de práctica</label><div className="fund-input"><input id="fund-amount" inputMode="decimal" value={value} onChange={e=>setValue(e.target.value)} maxLength={16} aria-describedby={error?'fund-error':undefined}/><Select value={token} onValueChange={v=>{if(v)setToken(v as TokenId);}}><SelectTrigger aria-label="Token del cofre"><SelectValue/></SelectTrigger><SelectContent>{TOKENS.map(t=><SelectItem key={t} value={t}>{t}</SelectItem>)}</SelectContent></Select></div><p className="available-balance">Disponible: {formatted(save.balances[token])} {token}</p>{error?<p id="fund-error" role="alert" className="form-error">{error}</p>:null}<button className="primary-button fund-button" type="submit"><ArrowDownToLine size={15}/> Depositar en el cofre</button><button type="button" className="withdraw-button" disabled={save.chest[token]===0} onClick={()=>{try{onWithdraw(token,save.chest[token]);setError('');}catch(err){setError(err instanceof Error?err.message:'No se pudo retirar.');}}}><ArrowUpFromLine size={14}/> Retirar {token} a mi saldo</button></form><div className="loot-note"><Shield size={14}/> Pruebas locales. No se envían transacciones.</div></section></>;
}
