'use client';
import { useCallback, useEffect, useRef, useState } from 'react';
import { ArrowDownLeft, ArrowRight, ArrowUpRight, Castle, Check, ChevronRight, CircleHelp, Coins, Droplets, Expand, FlaskConical, Flag, Gem, Heart, Leaf, Pause, Play, RotateCcw, Shield, Skull, Sparkles, Swords, Timer, Trophy, Volume2, VolumeX, Zap } from 'lucide-react';
import { Dialog, DialogContent, DialogDescription, DialogTitle } from '@/components/ui/dialog';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { DUNGEONS, createState, type GameState } from '@/lib/game/physics';
import { PARTS, CLASSIC_SOURCE, type PartId } from '@/lib/game/catalog';
import type { Engine } from '@/lib/game/scene';
import { VaultEditor } from './vault-editor';
import { TOKENS, STORAGE_KEY, REWARDS, newSave, readSave, transfer, claimReward, customDungeon, formatted, type Save, type TokenId } from '@/lib/game/economy';
import { registerGameTools } from '@/lib/game/webmcp';

function Token({token, small=false}: {token: string; small?: boolean}) {
  return <span className={`token token-${token.toLowerCase()} ${small?'small':''}`}>{token==='SLP'?<FlaskConical/>:token==='AXS'?<Gem/>:<Shield/>}</span>;
}
function formatTime(seconds: number) { return `${Math.floor(seconds / 60).toString().padStart(2,'0')}:${Math.floor(seconds % 60).toString().padStart(2,'0')}`; }
export default function VaultGame() {
  const host=useRef<HTMLDivElement>(null), engine=useRef<Engine|null>(null), shell=useRef<HTMLDivElement>(null);
  const [game,setGame]=useState<GameState>(()=>createState(DUNGEONS[0]));
  const [levelIndex,setLevelIndex]=useState(0), [loaded,setLoaded]=useState(false), [error,setError]=useState('');
  const [part,setPart]=useState<PartId|null>(null), [help,setHelp]=useState(false), [view,setView]=useState('raid');
  const [save,setSave]=useState<Save>(newSave),[toast,setToast]=useState(''),[walletOpen,setWalletOpen]=useState(false);
  const saveRef=useRef(save),modeRef=useRef('raid'),lastPhase=useRef('ready');
  const commit=useCallback((next:Save)=>{saveRef.current=next;setSave(next);try{localStorage.setItem(STORAGE_KEY,JSON.stringify(next));}catch{setToast('El navegador no permite guardar. La sesión continuará en memoria.');}},[]);
  useEffect(()=>{try{const restored=readSave();saveRef.current=restored;setSave(restored);}catch(err){setToast(err instanceof Error?err.message:'No se pudo recuperar el guardado.');}},[]);
  useEffect(()=>{if(!toast)return;const timeout=setTimeout(()=>setToast(''),5500);return()=>clearTimeout(timeout);},[toast]);
  const update=useCallback((next:GameState)=>{if(next.phase==='dead'&&lastPhase.current!=='dead'&&modeRef.current==='vault'&&saveRef.current.proofs>0)commit({...saveRef.current,proofs:0,validated:false});lastPhase.current=next.phase;setGame(next);},[commit]);
  useEffect(()=>{let cancelled=false;import('@/lib/game/scene').then(({createEngine})=>{
    if(cancelled||!host.current)return;
    try {engine.current=createEngine(host.current,update,(message)=>{if(message)setError(message);else setLoaded(true);});
      if(process.env.NODE_ENV === 'development')(window as unknown as {__WAXIS_DEBUG:()=>GameState}).__WAXIS_DEBUG=()=>engine.current!.getState();}
    catch {setError('No se pudo iniciar WebGL. Activa la aceleración gráfica de tu navegador y recarga.');}
  }).catch(()=>setError('No se pudo cargar el juego. Recarga para volver a intentarlo.'));
  return ()=>{cancelled=true;engine.current?.dispose();engine.current=null;};},[update]);
  const selectLevel=(index:number)=>{setLevelIndex(index);modeRef.current='raid';setView('raid');engine.current?.setLevel(DUNGEONS[index]);};
  const changeView=(value:string)=>{if(value==='parts'){if(engine.current?.getState().phase==='playing')engine.current.pause();setPart('grass-snake');return;}modeRef.current=value;setView(value);engine.current?.setLevel(value==='vault'?customDungeon(saveRef.current):DUNGEONS[levelIndex]);};
  const editTrap=(index:number,partId:PartId,x:number)=>{const next={...saveRef.current,traps:saveRef.current.traps.map((t,i)=>i===index?{...t,part:partId,x}:t),proofs:0,validated:false};commit(next);engine.current?.setLevel(customDungeon(next));};
  const moveTokens=useCallback((token:TokenId,units:number,kind:'deposit'|'withdraw')=>{commit(transfer(saveRef.current,token,units,kind));setToast(kind==='deposit'?'Botín de práctica añadido al cofre.':'Fondos de práctica devueltos a tu saldo.');},[commit]);
  const claim=()=>{if(engine.current?.getState().phase!=='won'||modeRef.current!=='raid')return;try{commit(claimReward(saveRef.current,DUNGEONS[levelIndex].id));setToast('Botín reclamado. Tu saldo de práctica se actualizó.');}catch(err){setToast(err instanceof Error?err.message:'No se pudo reclamar.');}};
  const confirmTest=()=>{if(engine.current?.getState().phase!=='won'||modeRef.current!=='vault'||saveRef.current.validated)return;const proofs=Math.min(2,saveRef.current.proofs+1);commit({...saveRef.current,proofs,validated:proofs===2});if(proofs<2){engine.current.restart();engine.current.start();}else setToast('Dos recorridos completados. Tu defensa quedó validada y guardada.');};
  useEffect(()=>registerGameTools({read:()=>({balances:saveRef.current.balances,chest:saveRef.current.chest,unit:1000000,mode:'practice',game:engine.current?.getState()??null}),transfer:moveTokens,start:(id:string)=>{if(!engine.current)throw new Error('El juego sigue cargando.');if(id==='my-vault'){modeRef.current='vault';setView('vault');engine.current.setLevel(customDungeon(saveRef.current));}else{const index=DUNGEONS.findIndex(d=>d.id===id);if(index<0)throw new Error('Mazmorra desconocida.');setLevelIndex(index);modeRef.current='raid';setView('raid');engine.current.setLevel(DUNGEONS[index]);}engine.current.start();return {started:id};}}),[moveTokens]);
  const openPart=(id:PartId)=>{if(game.phase==='playing')engine.current?.pause();setPart(id);};
  const ownVault=view==='vault',level=ownVault?customDungeon(save):DUNGEONS[levelIndex],playing=game.phase==='playing';
  const reward=REWARDS[DUNGEONS[levelIndex].id],claimed=save.claimed.includes(DUNGEONS[levelIndex].id);
  return <div className="game-app">
    <header className="topbar">
      <a href="/" className="brand" aria-label="Waxis inicio"><span className="brand-mark"><Castle size={24}/></span><div>WAXIS<span>VAULT RAIDERS</span></div></a>
      <Tabs value={part!==null?'parts':view} onValueChange={value=>changeView(String(value))} className="main-tabs">
        <TabsList><TabsTrigger value="raid"><Swords/> Asaltar</TabsTrigger><TabsTrigger value="vault"><Castle/> Mi mazmorra</TabsTrigger><TabsTrigger value="parts"><Sparkles/> Partes Axie</TabsTrigger></TabsList>
      </Tabs>
      <div className="top-wallet"><span className="practice-badge"><span/> MODO PRÁCTICA</span><button className="wallet-balance" onClick={()=>{if(playing)engine.current?.pause();setWalletOpen(true);}} aria-label="Ver saldos de práctica"><Token token="SLP" small/> {formatted(save.balances.SLP)} <em>SLP</em><ChevronRight size={13}/></button><button className="help-button icon-button" onClick={()=>{if(playing)engine.current?.pause();setHelp(true);}} aria-label="Cómo jugar"><CircleHelp size={20}/></button></div>
    </header>
    <main className="main-content">
      <div className="page-heading"><div><div className="eyebrow"><span className="live-dot"/> EXPEDICIÓN A LUNACIA <span className="slash">/</span> AXIE CLASSIC</div><h1>{ownVault?'Tu mazmorra.':'Pequeño Axie.'} <span>{ownVault?'Tus reglas.':'Gran botín.'}</span></h1></div><div className="session-mark"><span>ELIGE TU RUTA</span><div>{DUNGEONS.map((d,i)=><button key={d.id} className={!ownVault&&i===levelIndex?'current':''} onClick={()=>selectLevel(i)} aria-label={`Mazmorra ${i+1}: ${d.name}`} aria-pressed={i===levelIndex}>0{i+1}</button>)}</div></div></div>
      <div className="play-layout">
        <section className="dungeon-panel" ref={shell}>
          <div className="dungeon-heading"><div className="dungeon-name"><span className="level-number">{ownVault?<Castle size={20}/>:String(levelIndex+1).padStart(2,'0')}</span><div><h2>{level.name}</h2><p><span className="difficulty-dot"/>{level.difficulty}<span>·</span>{level.subtitle}</p></div></div><div className="game-tools"><button className="icon-button" onClick={()=>engine.current?.restart()} aria-label="Reiniciar intento" title="Reiniciar · R"><RotateCcw size={18}/></button><button className="icon-button" onClick={()=>engine.current?.pause()} disabled={!playing&&game.phase!=='paused'} aria-label={playing?'Pausar':'Continuar'} title="Pausa · P">{game.phase==='paused'?<Play size={18}/>:<Pause size={18}/>}</button><button className="icon-button" onClick={()=>{if(!document.fullscreenElement)shell.current?.requestFullscreen?.().catch(()=>setHelp(true));else document.exitFullscreen?.();}} aria-label="Pantalla completa"><Expand size={18}/></button></div></div>
          <div className="game-viewport" onPointerDown={e=>{if(!(e.target as HTMLElement).closest('button')){e.preventDefault();engine.current?.jump();}}}>
            <div className="three-host" ref={host}/>
            <div className="in-game-hud"><div className="health"><Heart size={15} fill="currentColor"/><div className="health-track"><div style={{width:`${game.hp}%`}}/></div><span>{Math.ceil(game.hp)}</span></div><div className="run-stats"><span><Skull size={14}/>{game.deaths}</span><span><Timer size={14}/>{formatTime(game.time)}</span></div></div>
            <div className="world-caption entry-caption"><ArrowDownLeft size={15}/> ENTRADA</div><div className="world-caption vault-caption"><Gem size={13}/> EL COFRE TE ESPERA</div>
            {game.poison>0||game.slowActions>0?<div className="status-effects">{game.poison>0?<span><Droplets size={14}/> Poison ×{game.poison}</span>:null}{game.slowActions>0?<span><Zap size={14}/> Speed− · {game.slowActions} saltos</span>:null}</div>:null}
            {!loaded&&!error?<div className="loading-game"><span className="loading-orbit"/>Preparando a tu Axie…</div>:null}
            {error?<div className="game-overlay"><CircleHelp size={32}/><h3>No pudimos abrir la mazmorra</h3><p>{error}</p><button className="primary-button" onClick={()=>location.reload()}>Volver a cargar</button></div>:null}
            {loaded&&game.phase==='ready'?<div className="start-callout"><span>EL TESORO ESTÁ ARRIBA. TÚ ELIGES EL SALTO.</span><button className="primary-button" onClick={()=>{engine.current?.start();(document.activeElement as HTMLElement)?.blur();}}><Play size={17} fill="currentColor"/> {ownVault?'Probar mi defensa':'Entrar a la mazmorra'}<ArrowRight size={17}/></button><p>Espacio, clic o toque para saltar</p></div>:null}
            {game.phase==='paused'?<div className="game-overlay"><Pause size={30}/><h3>Una pequeña pausa</h3><p>El cofre puede esperar.</p><button className="primary-button" onClick={()=>engine.current?.pause()}><Play size={17}/> Continuar</button></div>:null}
            {game.phase==='dead'?<div className="game-overlay"><Skull size={34}/><span className="eyebrow">INTENTO {game.deaths}</span><h3>Tan cerca del tesoro…</h3><p>{game.reason}</p><button className="primary-button" onClick={()=>{engine.current?.restart();engine.current?.start();}}><RotateCcw size={17}/> Otro intento</button></div>:null}
            {game.phase==='won'?<div className="game-overlay victory"><Trophy size={40}/><span className="eyebrow">INCURSIÓN COMPLETADA</span><h3>{ownVault?(save.validated?'¡Defensa validada!':'¡Recorrido completado!'):'¡El cofre es tuyo!'}</h3><p>{game.jumps} saltos · {formatTime(game.time)} · {game.deaths} caídas</p>{ownVault?<><p>{save.validated?'Tu diseño quedó guardado en este navegador.':'Dos recorridos consecutivos prueban que el cofre es alcanzable.'}</p><button className="primary-button" disabled={save.validated} onClick={confirmTest}><Check size={17}/>{save.validated?'Guardada':save.proofs===0?'Confirmar y hacer segunda prueba':'Confirmar y guardar defensa'}</button></>:<><button className="primary-button" onClick={claim} disabled={claimed}>{claimed?<Check size={17}/>:<Gem size={17}/>} {claimed?'Botín ya reclamado':'Reclamar '+formatted(reward.units)+' '+reward.token}</button><button className="secondary-button" onClick={()=>selectLevel((levelIndex+1)%DUNGEONS.length)}>Siguiente mazmorra<ArrowRight size={17}/></button></>}</div>:null}
          </div>
          <div className="control-bar"><div><kbd>ESPACIO</kbd><span>o clic para saltar</span><span className="control-divider"/><span className="wall-tip"><ArrowUpRight size={17}/> Salta contra una pared para rebotar</span></div><button onClick={()=>{if(playing)engine.current?.pause();setHelp(true);}}>Cómo jugar <CircleHelp size={16}/></button></div>
        </section>
        <aside className={'raid-sidebar '+(ownVault?'editor-sidebar':'')}>
          {ownVault?<VaultEditor save={save} onEdit={editTrap} onFund={(token,units)=>moveTokens(token,units,'deposit')} onWithdraw={(token,units)=>moveTokens(token,units,'withdraw')} onInspect={openPart}/>:<>
          <section className="loot-card"><div className="card-overline"><span><Gem size={15}/> EL BOTÍN</span><span className="tiny-badge">DEMO</span></div><div className="loot-value"><Token token={reward.token}/><div><strong>{claimed?'0':formatted(reward.units)}</strong><span>{reward.token}</span></div><ArrowUpRight size={19}/></div><p>{claimed?'Cofre reclamado. Sigue practicando.':'Llega al cofre para reclamarlo.'}</p><div className="loot-line"/><div className="loot-detail"><span>Recompensa por llegar</span><strong>100%</strong></div><div className="loot-detail"><span>Red</span><strong>Simulación local</strong></div><div className="loot-note"><Shield size={14}/> Fondos de práctica. Sin valor real.</div></section>
          <section className="defense-card"><div className="card-overline"><span><Shield size={15}/> LAS DEFENSAS</span><span>3 PARTES</span></div><div className="trap-list">{level.traps.map((trap,i)=>{const p=PARTS[trap.part];return <button className="trap-row" key={`${trap.part}-${i}`} onClick={()=>openPart(trap.part)}><div className={`part-thumb ${trap.part}`}><img src={'/assets/'+trap.part+'-part.png'} alt=""/></div><div><strong>{p.name}</strong><span>{p.short}</span></div><ChevronRight size={15}/></button>;})}</div><a className="source-link" href={CLASSIC_SOURCE} target="_blank" rel="noreferrer">Habilidades de Axie Classic <ArrowUpRight size={14}/></a></section>
          <div className="axie-note"><span className="axie-status"><Leaf size={20}/></span><div><strong>Buba está listo</strong><span>Tu compañero de incursión</span></div><span className="live-dot"/></div>
        </>}
        </aside>
      </div>
      <div className="below-game"><span><span className="live-dot"/> UN BOTÓN. EL MOMENTO PERFECTO.</span><p>Corre automáticamente. Rebota en las paredes. Encuentra el camino al cofre.</p><span>HECHO PARA LUNACIA <Sparkles size={13}/></span></div>
    </main>
    <footer><span>WAXIS <em>/</em> HACKATHON BUILD 0.1</span><span>Axies y partes oficiales · Adaptación de plataformas independiente</span><a href="https://github.com/axieinfinity/axie-starter-3d-assets" target="_blank" rel="noreferrer">Recursos de Axie <ArrowUpRight size={12}/></a></footer>
    <Dialog open={part!==null} onOpenChange={open=>{if(!open){setPart(null);}}}><DialogContent className="part-dialog">{part?<><DialogTitle>{PARTS[part].name}</DialogTitle><DialogDescription>{PARTS[part].slot} · {PARTS[part].class} · Axie Classic, nivel 1</DialogDescription><div className="part-detail-hero"><img src={PARTS[part].image} alt={`Ilustración oficial de ${PARTS[part].card}`}/><div><span className="eyebrow">HABILIDAD ORIGINAL</span><h3>{PARTS[part].card}</h3><p>{PARTS[part].effect}</p><div className="card-stats"><span><Swords size={15}/>{PARTS[part].attack}</span><span><Shield size={15}/>{PARTS[part].shield}</span><span><Zap size={15}/>{PARTS[part].energy}</span></div></div></div><div className="adaptation-note"><strong>En esta mazmorra</strong><p>{PARTS[part].arcade}</p><small>Daño, movimiento y duración adaptados al plataformas; no son las reglas de combate de Classic.</small></div><a className="source-link" href={CLASSIC_SOURCE} target="_blank" rel="noreferrer">Consultar carta original <ArrowUpRight size={15}/></a></>:null}</DialogContent></Dialog>
    <Dialog open={walletOpen} onOpenChange={setWalletOpen}><DialogContent className="help-dialog wallet-dialog"><DialogTitle>Tu saldo de práctica</DialogTitle><DialogDescription>SLP, AXS y RON simulados · Guardados en este navegador</DialogDescription><div className="wallet-tokens">{TOKENS.map(t=><div key={t}><Token token={t}/><div><strong>{formatted(save.balances[t])} <small>{t}</small></strong><span>En tu cofre: {formatted(save.chest[t])} {t}</span></div></div>)}</div><div className="adaptation-note">Los cofres de las tres incursiones entregan botín una sola vez. Los depósitos mueven saldo de práctica a tu cofre y los retiros lo devuelven. Probar tu propia defensa no genera recompensas.</div><h3 className="history-title">Últimos movimientos</h3>{save.history.length===0?<p className="history-empty">Aún no hay movimientos. Asalta un cofre o deposita botín en tu mazmorra.</p>:<div className="history-list">{save.history.slice(0,6).map(e=><div key={e.id}><span>{e.kind==='deposit'?'Depósito al cofre':e.kind==='withdraw'?'Retiro del cofre':'Botín reclamado'}</span><strong>{e.kind==='deposit'?'−':'+'}{formatted(e.units)} {e.token}</strong></div>)}</div>}<span className="wallet-network"><Shield size={14}/> Sin conexión a Ronin ni fondos reales</span></DialogContent></Dialog>
    {toast?<div className="game-toast" role="status"><Check size={17}/>{toast}</div>:null}
    <Dialog open={help} onOpenChange={setHelp}><DialogContent className="help-dialog"><DialogTitle>Un botón. Mucha habilidad.</DialogTitle><DialogDescription>Guía de la incursión</DialogDescription><div className="help-steps"><p><span>01</span><strong>Buba corre solo.</strong> Tú decides cuándo saltar con Espacio, clic o toque.</p><p><span>02</span><strong>Usa las paredes.</strong> Al saltar contra una pared, cambias de dirección. También puedes saltar mientras te deslizas.</p><p><span>03</span><strong>Evita las partes.</strong> El veneno resta vida por salto; Speed− reduce la velocidad. Thorny Caterpillar hace más daño si tienes un efecto negativo.</p><p><span>04</span><strong>Alcanza el cofre.</strong> R reinicia el intento. P pausa. Puedes reintentar sin límite.</p></div><div className="adaptation-note">Este prototipo usa arte oficial de Axie, física propia y una economía de práctica. Las adaptaciones de cada habilidad están en su ficha.</div></DialogContent></Dialog>
  </div>;
}
