export type Pattern = 'bolt'|'arc'|'fan'|'burst'|'dash'|'bite'|'sniper'|'aura'|'barrier'|'boomerang';
export type Trigger = 'fire'|'hit'|'struck'|'break'|'end';
export type Target = 'self'|'target'|'front'|'team'|'adjacent';
export interface Rule { on:Trigger; op:string; value:number; target:Target; when:string; status?:string }
export interface Recipe { pattern:Pattern; summary:string; rules:Rule[] }
const r=(on:Trigger,op:string,value=1,target:Target='self',when='always',status?:string):Rule=>({on,op,value,target,when,status});
const status=(on:Trigger,key:string,n=2,target:Target='target',when='always')=>r(on,'status',n,target,when,key);
const hit=(op:string,value=1,when='always',target:Target='target')=>r('hit',op,value,target,when);
const fire=(op:string,value=1,when='always',target:Target='self')=>r('fire',op,value,target,when);
const m=(pattern:Pattern,summary:string,...rules:Rule[]):Recipe=>({pattern,summary,rules});
/** Explicit, reviewed mapping. No fallback powers inferred from names or artwork. */
export const RECIPES:Record<string,Recipe>={
'aquatic-back-02':m('barrier','Barrera inmune a críticos durante su ciclo.',status('fire','critical-block',1,'self')),
'aquatic-back-04':m('bolt','Dispara; acertar a un Axie que no saltó este ciclo acelera la recarga.',hit('draw',1,'target-idle','self')),
'aquatic-back-06':m('dash','Al recibir un pisotón gana Speed+ durante 2 ciclos.',status('struck','speed-up',2,'self')),
'aquatic-back-08':m('barrier','Romper su escudo carga Attack+ una vez por ciclo.',status('break','attack-up',1,'self')),
'aquatic-back-10':m('bite','Mordida que cura 10 PV por cada Anemone equipada al acertar.',hit('anemone-heal',10,'always','self')),
'aquatic-back-12':m('dash','Con otras 2 defensas operativas, espera a que el asaltante no salte para embestir.',fire('target',1,'combo3', 'self')),
'aquatic-horn-02':m('bite','Inflige 150% de daño si el asaltante no ha saltado este ciclo.',hit('damage',1.5,'target-idle')),
'aquatic-horn-04':m('bite','Añade como daño el 30% del escudo que tenía al empezar el ciclo.',hit('shield-damage',.3)),
'aquatic-horn-06':m('bite','Acertar a Beast, Bug o Mech le da Attack+.',status('hit','attack-up',1,'self','target-beast-bug-mech')),
'aquatic-horn-08':m('arc','Proyectil que cura 10 PV por cada Anemone equipada al acertar.',hit('anemone-heal',10,'always','self')),
'aquatic-horn-10':m('bolt','El proyectil termina el Último Aliento del asaltante.',hit('end-laststand')),
'aquatic-horn-12':m('boomerang','Shuriken: un golpe mortal impide entrar en Último Aliento.',hit('no-laststand')),
'aquatic-mouth-02':m('bite','Mordida con 120% de daño si la defensa tiene menos del 50% de vida.',hit('damage',1.2,'self-low')),
'aquatic-mouth-04':m('bite','Se cura por el daño efectivo de su mordida.',hit('lifesteal',1,'always','self')),
'aquatic-mouth-08':m('bite','Acertar a Plant, Reptile o Dusk le da Attack+.',status('hit','attack-up',1,'self','target-plant-reptile-dusk')),
'aquatic-mouth-10':m('dash','Con menos del 50% de vida busca al asaltante herido a mayor distancia.',fire('target',1,'self-low')),
'aquatic-tail-02':m('dash','Con otra defensa Aquatic gana Speed+ durante 2 ciclos.',status('fire','speed-up',2,'self','aquatic-combo')),
'aquatic-tail-04':m('bite','Con otra defensa operativa gana 1 energía para su próxima ráfaga.',fire('energy',1,'combo')),
'aquatic-tail-06':m('arc','Burbuja que aplica Jinx: los pisotones no pueden ser críticos durante 4 saltos.',status('hit','jinx',4)),
'aquatic-tail-08':m('arc','Esfera que aplica Chill: bloquea Último Aliento durante 4 saltos.',status('hit','chill',4)),
'aquatic-tail-10':m('dash','Inflige 120% de daño si es la primera defensa del orden.',hit('damage',1.2,'first')),
'aquatic-tail-12':m('sniper','Fija al asaltante lejano y dispara hacia su posición. Con un solo rival no cambia de objetivo.',fire('target')),
'beast-back-02':m('bite','Con otras 2 defensas operativas, su golpe es crítico garantizado.',hit('critical',1,'combo3')),
'beast-back-04':m('bite','Acertar a Aquatic, Bird o Dawn acelera su próxima recarga.',hit('draw',1,'target-aquatic-bird-dawn','self')),
'beast-back-06':m('dash','Cuando alguien entra en Último Aliento adelanta su siguiente embestida.',fire('priority',1,'any-laststand')),
'beast-back-08':m('bolt','Flecha con 200% de daño durante su Último Aliento.',hit('damage',2,'self-laststand')),
'beast-back-10':m('barrier','Un pisotón Plant o Reptile aplica Stun al atacante una vez por ciclo.',status('struck','stun',1,'target','target-plant-reptile')),
'beast-back-12':m('burst','Lanza tres proyectiles consecutivos.',fire('repeat',3)),
'beast-horn-02':m('dash','Crítico garantizado cuando ocupa la primera posición del orden.',hit('critical',1,'first')),
'beast-horn-04':m('bite','Cada crítico de una defensa aliada le aporta 1 energía.',fire('team-critical-energy')),
'beast-horn-06':m('barrier','Con otra defensa operativa obtiene un 20% más de escudo.',fire('shield-multiplier',1.2,'combo')),
'beast-horn-08':m('dash','Aplica Aroma a sí misma: atrae hacia ella el siguiente pisotón cercano.',status('fire','aroma',1,'self')),
'beast-horn-10':m('bite','Sus golpes críticos infligen 200% del daño base.',hit('critical-multiplier',2)),
'beast-horn-12':m('dash','Con otra defensa operativa gana Speed+ durante 2 ciclos.',status('fire','speed-up',2,'self','combo')),
'beast-mouth-02':m('bite','Con otra Nut Cracker operativa inflige 120% de daño.',hit('damage',1.2,'nut-combo')),
'beast-mouth-04':m('bolt','Onda sonora que destruye 1 energía del asaltante.',hit('destroy-energy')),
'beast-mouth-08':m('bolt','Con menos del 30% de vida aplica Lethal: el próximo impacto será crítico.',status('hit','lethal',1,'target','self-critical')),
'beast-mouth-10':m('aura','Da Speed+ y Morale+ a las defensas aliadas durante 2 ciclos.',status('fire','speed-up',2,'team'),status('fire','morale-up',2,'team')),
'beast-tail-02':m('aura','Acumula 1 energía por activación para potenciar el siguiente ataque aliado.',fire('energy')),
'beast-tail-04':m('bite','Con otra defensa operativa roba 1 energía al asaltante.',hit('steal',1,'combo')),
'beast-tail-06':m('dash','Con otras 3 defensas operativas garantiza Último Aliento si cae este ciclo.',status('fire','guaranteed-laststand',1,'self','combo4')),
'beast-tail-08':m('bolt','Si es la primera del orden, roba una carta: su próxima recarga se acorta.',fire('draw',1,'first')),
'beast-tail-10':m('bolt','Con otra Nut Cracker operativa inflige 120% de daño.',hit('damage',1.2,'nut-combo')),
'beast-tail-12':m('dash','Embestida corta. Su regla de omitir al rival más cercano requiere varios asaltantes; aquí solo hay uno.'),
'bird-back-02':m('arc','Al acertar aplica Fear por 1 salto; al recibir un pisotón se aplica Fear a sí misma.',status('hit','fear',1),status('struck','fear',1,'self')),
'bird-back-04':m('bolt','Flecha que aplica Chill durante 4 saltos.',status('hit','chill',4)),
'bird-back-06':m('bolt','Proyectil que aplica Jinx durante 4 saltos.',status('hit','jinx',4)),
'bird-back-08':m('bolt','Transfiere sus efectos negativos al asaltante al acertar.',hit('transfer')),
'bird-back-10':m('dash','Con vida inferior al 50% fija al asaltante si es Aquatic.',fire('target',1,'self-low-aquatic')),
'bird-back-12':m('fan','Lanza dos plumas si tiene algún efecto negativo.',fire('repeat',2,'self-debuffed')),
'bird-horn-02':m('arc','Lanza un huevo y se aplica Aroma hasta el próximo ciclo.',status('fire','aroma',1,'self')),
'bird-horn-04':m('aura','Aplica Attack+ a todas las defensas aliadas.',status('fire','attack-up',1,'team')),
'bird-horn-06':m('dash','Otra Trump operativa aumenta su daño al 120%.',hit('damage',1.2,'trump-chain')),
'bird-horn-08':m('sniper','Bloquea los pisotones de tipo cuerno durante el siguiente salto.',status('hit','disable-horn',1)),
'bird-horn-10':m('sniper','Disparo dirigido. La selección que omite al rival cercano no cambia nada con un solo asaltante.'),
'bird-horn-12':m('dash','Con otra carta Lunge operativa inflige 120% de daño.',hit('damage',1.2,'lunge-chain')),
'bird-mouth-02':m('bolt','La onda ignora el escudo y aplica Sleep al asaltante.',hit('ignore-shield'),status('hit','sleep',1)),
'bird-mouth-04':m('bite','Aplica Attack−: el siguiente pisotón hace menos daño.',status('hit','attack-down',1)),
'bird-mouth-08':m('dash','Con menos del 50% de vida fija al asaltante si es Bug.',fire('target',1,'self-low-bug')),
'bird-mouth-10':m('sniper','Fija al asaltante veloz. En una incursión individual solo existe un objetivo.',fire('target')),
'bird-tail-02':m('bolt','Inflige 120% de daño si ataca primero en el orden.',hit('damage',1.2,'first')),
'bird-tail-04':m('barrier','Obtiene 20% más de escudo por cada efecto negativo propio.',fire('debuff-shield',.2)),
'bird-tail-06':m('bolt','Proyectil potente que aplica 2 Attack− a la propia defensa.',status('fire','attack-down',2,'self')),
'bird-tail-08':m('dash','Omite al asaltante mientras esté en Último Aliento.',fire('skip-laststand')),
'bird-tail-10':m('fan','Abanico que aplica Chill durante 4 saltos.',status('hit','chill',4)),
'bird-tail-12':m('bolt','Disparo gratuito que consume 30% de la vida máxima de la propia defensa.',fire('self-damage',.3)),
'bug-back-02':m('barrier','Romper su escudo aplica Stun al atacante una vez por ciclo.',status('break','stun',1)),
'bug-back-04':m('arc','Con otra defensa Bug operativa aplica 2 Poison.',status('hit','poison',2,'target','chain')),
'bug-back-06':m('bolt','Onda que aplica Attack− al asaltante.',status('hit','attack-down',1)),
'bug-back-08':m('bite','Inflige 150% de daño a un asaltante Bug.',hit('damage',1.5,'target-bug')),
'bug-back-10':m('bolt','Impide curarse durante 2 saltos; este efecto no se limpia.',status('hit','heal-block',2)),
'bug-back-12':m('bolt','Aplica Fragile durante 2 saltos: el escudo recibe el doble de daño.',status('hit','fragile',2)),
'bug-horn-02':m('dash','Embestida anunciada: aplica Speed− durante 2 saltos.',status('hit','speed-down',2)),
'bug-horn-04':m('bolt','Con otra Bug Signal operativa roba 1 energía.',hit('steal',1,'bug-signal-chain')),
'bug-horn-06':m('arc','Aplica Fear si el asaltante conserva escudo.',status('hit','fear',1,'target','target-shielded')),
'bug-horn-08':m('bite','Inflige 130% de daño a objetivos con escudo.',hit('damage',1.3,'target-shielded')),
'bug-horn-10':m('bolt','Con otra defensa operativa descarta un ataque preparado del asaltante.',hit('discard',1,'combo')),
'bug-horn-12':m('aura','Con una defensa Plant operativa obtiene 1 energía.',fire('energy',1,'plant-combo')),
'bug-mouth-02':m('bite','Se cura por el daño efectivo de su mordida.',hit('lifesteal',1,'always','self')),
'bug-mouth-04':m('bite','Con otra defensa operativa descarta un ataque preparado del asaltante.',hit('discard',1,'combo')),
'bug-mouth-08':m('bite','Con otra defensa Bug operativa aplica Fear durante 2 saltos.',status('hit','fear',2,'target','chain')),
'bug-mouth-10':m('bite','Con otra defensa operativa inflige el doble de daño.',hit('damage',2,'combo')),
'bug-tail-02':m('arc','Aplica Stench por 3 saltos. La pérdida de prioridad no cambia con un único asaltante.',status('hit','stench',3)),
'bug-tail-04':m('burst','Con otra defensa operativa dispara dos veces.',fire('repeat',2,'combo')),
'bug-tail-06':m('barrier','Un pisotón Aquatic o Bird aplica Stun una vez por ciclo.',status('struck','stun',1,'target','target-aquatic-bird')),
'bug-tail-08':m('bolt','Con otra defensa operativa bloquea los pisotones cuerpo a cuerpo durante 1 salto.',status('hit','disable-melee',1,'target','combo')),
'bug-tail-10':m('burst','Durante Último Aliento hace 200% de daño y consume ese estado al terminar el ataque.',hit('damage',2,'self-laststand'),r('end','end-laststand',1,'self')),
'bug-tail-12':m('burst','Espinas por proximidad: 130% de daño contra objetivos con efectos negativos.',hit('damage',1.3,'target-debuffed')),
'plant-back-02':m('arc','Con otras 2 defensas operativas fija al asaltante si es Bird.',fire('target',1,'combo3-bird')),
'plant-back-04':m('aura','Pulso que cura 24 PV a la propia defensa.',fire('heal',24)),
'plant-back-06':m('aura','Limpia sus efectos negativos, incluso durante Stun o Fear.',fire('cleanse')),
'plant-back-08':m('barrier','Recibir un pisotón Aquatic le aporta 1 energía.',r('struck','energy',1,'self','target-aquatic')),
'plant-back-10':m('aura','Limpia los efectos negativos de la primera defensa del orden.',fire('cleanse',1,'always','front')),
'plant-back-12':m('barrier','Si su escudo sobrevive al ciclo, acelera la próxima recarga.',r('end','draw',1,'self','self-shielded')),
'plant-horn-02':m('bite','Con otra defensa Plant operativa inflige 120% de daño.',hit('damage',1.2,'chain')),
'plant-horn-04':m('bite','Romper su escudo aumenta el daño al 120% hasta el próximo ciclo.',hit('damage',1.2,'shield-broken')),
'plant-horn-06':m('aura','Pulso que cura 24 PV a la propia defensa.',fire('heal',24)),
'plant-horn-08':m('aura','Cura 54 PV a la primera defensa del orden.',fire('heal',54,'always','front')),
'plant-horn-10':m('burst','Espinas con 120% de daño si es la última defensa del orden.',hit('damage',1.2,'last')),
'plant-horn-12':m('sniper','Dispara una semilla hacia el asaltante. La prioridad por velocidad no cambia con un solo rival.',fire('target')),
'plant-mouth-02':m('bite','Con otra defensa operativa roba 1 energía al asaltante.',hit('steal',1,'combo')),
'plant-mouth-04':m('bite','Se cura por el daño efectivo de su mordida.',hit('lifesteal',1,'always','self')),
'plant-mouth-08':m('bite','Se cura por el daño efectivo si el asaltante es Plant.',hit('lifesteal',1,'target-plant','self')),
'plant-mouth-10':m('aura','Cura 24 PV a la primera defensa del orden.',fire('heal',24,'always','front')),
'plant-tail-02':m('bolt','Lanza zanahorias; romper su escudo aporta 1 energía para un disparo extra, una vez por ciclo.',r('break','energy')),
'plant-tail-04':m('barrier','Un pisotón Beast, Bug o Mech acelera su próxima recarga.',r('struck','draw',1,'self','target-beast-bug-mech')),
'plant-tail-06':m('barrier','Al recibir un pisotón bloquea los ataques a distancia del atacante durante 1 salto.',status('struck','disable-ranged',1)),
'plant-tail-08':m('fan','Gas que aplica Poison al atacar y al recibir un pisotón.',status('hit','poison',1),status('struck','poison',1)),
'plant-tail-10':m('barrier','Con aliados operativos, un asaltante Aquatic no puede dirigirle el pisotón.',fire('aquatic-cover')),
'plant-tail-12':m('bite','Aplica bloqueo de ataques de boca durante el siguiente salto.',status('hit','disable-mouth',1)),
'reptile-back-02':m('barrier','Romper su escudo acelera la siguiente recarga.',r('break','draw')),
'reptile-back-04':m('fan','Con otras 2 defensas operativas fija al asaltante con escudo bajo.',fire('target',1,'combo3')),
'reptile-back-06':m('fan','Con una defensa Plant operativa obtiene el doble de escudo.',fire('shield-multiplier',2,'plant-combo')),
'reptile-back-08':m('barrier','Refleja al atacante el 40% del daño de pisotones cuerpo a cuerpo.',r('struck','reflect-melee',.4)),
'reptile-back-10':m('barrier','Comparte el 15% de su escudo con las defensas adyacentes del orden.',fire('share-shield',.15,'always','adjacent')),
'reptile-back-12':m('bolt','Proyectil que aplica Speed− durante 2 saltos.',status('hit','speed-down',2)),
'reptile-horn-02':m('arc','Aplica Stench durante 3 saltos.',status('hit','stench',3)),
'reptile-horn-04':m('dash','Con otra carta Lunge operativa inflige 120% de daño.',hit('damage',1.2,'lunge-chain')),
'reptile-horn-06':m('bite','Inflige 130% de daño si el asaltante es más rápido que la defensa.',hit('damage',1.3,'target-faster')),
'reptile-horn-08':m('boomerang','Refleja el 40% del daño de pisotones de tipo a distancia.',r('struck','reflect-ranged',.4)),
'reptile-horn-10':m('bite','Aplica Speed− durante 2 saltos.',status('hit','speed-down',2)),
'reptile-horn-12':m('barrier','Recupera 4 puntos de escudo al iniciar cada ciclo.',fire('shield',4)),
'reptile-mouth-02':m('sniper','Fija al asaltante lejano; no hay otros rivales que omitir.',fire('target')),
'reptile-mouth-04':m('bite','Gana 1 energía si acierta a un asaltante más rápido.',hit('energy',1,'target-faster','self')),
'reptile-mouth-08':m('bite','Se cura por el daño efectivo contra un asaltante Aquatic.',hit('lifesteal',1,'target-aquatic','self')),
'reptile-mouth-10':m('bite','Con otras 2 defensas operativas aplica Stun al acertar.',status('hit','stun',1,'target','combo3')),
'reptile-tail-02':m('barrier','Reduce en 15% el daño recibido durante el ciclo.',status('fire','damage-reduction',1,'self')),
'reptile-tail-04':m('bolt','Acertar a un asaltante con una mejora activa aporta 1 energía.',hit('energy',1,'target-buffed','self')),
'reptile-tail-06':m('dash','Desde el quinto ciclo inflige 150% de daño.',hit('damage',1.5,'round5')),
'reptile-tail-08':m('barrier','El pisotón que rompe su escudo no causa daño sobrante a su vida.',fire('block-overflow')),
'reptile-tail-10':m('bolt','Aplica 2 Attack− si el asaltante ya está envenenado.',status('hit','attack-down',2,'target','target-poison')),
'reptile-tail-12':m('fan','Escupe veneno en arco y deja charcos; cada impacto aplica exactamente 1 Poison.',status('hit','poison',1)),
};
export const PATTERN_LABELS:Record<Pattern,string>={bolt:'Lanzador',arc:'Arco',fan:'Abanico',burst:'Ráfaga',dash:'Embestida',bite:'Mordida',sniper:'Disparo dirigido',aura:'Apoyo',barrier:'Barrera',boomerang:'Retorno'};
